Heroku/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('cla.urls')),
    path('register/',include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns =[
    path('register',views.register,name='register'),
    path('login',views.login,name = 'login'), 
    path('logout',views.logout,name = 'logout'),
    path('subscribe',views.subscribe,name = "subscribe"),
]

cla/urls.py
from django.urls import path
from . import views

app_name="cla"
urlpatterns =[
    path('',views.index,name='index'),
    path("about",views.about,name= "about"),
    path("computer",views.computer,name= "computer"),
    path("laptop",views.laptop,name= "laptop"),
    path("product",views.product,name= "product"),
    path("contact",views.contact,name= "contact"),
    path('cart', views.cart,name = 'cart'),
    path('checkout' ,views.checkout,name= 'checkout'),
    path('updateItem',views.updateItem,name='updateItem'),
    path('detail/<int:product_id>',views.detail,name='detail'),
    path('add_to_checkout/<int:product_id>',views.add_to_checkout,name='add_to_checkout'),
]

templates/detail.html
{% extends 'nohome_base.html' %}
{% block title %}{{product}} - Details{% endblock title %}
{% block content %}
<div class="container">
    <div class="row mt-2">
        
        <div class="col-md-6 justify-content-start d-flex p-4" style="min-height:80vh;box-sizing:border-box;">
            <img class="p-1 mb-auto" src="{{product.image_url}}" alt="" style="width: 80%; height:auto;">
        </div>
        <div class="col-md-6 p-4" style="box-sizing:border-box; color:black">
            <h1 class="h1 text-uppercase">{{product.product_name}}</h1>
            <h5 class="h5">$ {{product.product_price}}</h5>
            <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis dolor recusandae qui et voluptatum, ratione molestiae officiis neque iure! Aliquid id quisquam optio alias quidem vero voluptatibus, debitis asperiores fuga!
            Voluptatem non assumenda eligendi laboriosam commodi adipisci cupiditate obcaecati, debitis alias, expedita modi. Beatae cumque suscipit distinctio reiciendis, maiores ducimus itaque doloribus omnis, animi veniam excepturi praesentium obcaecati earum fugit.</p>
            <br><hr><br>
            <div class="p-2 border">
                <ul><br>
                    <div class="h6 btn btn-info">Special Offers:</div>
                    <hr>
                    <li>
                        <div>Lorem ipsum, dolor sit amet consectetur deleniti. Nostrum accusamus atque cupiditate error architecto beatae rem.</div>
                    </li><hr>
                    <li>
                        <div>Lorem ipsum dolor, sit amet consectetur at dolorum officiis porro velit voluptatibus eum deserunt minus nesciunt quo sequi.</div>
                    </li><hr>
                    <li>
                        <div>Lorem ipsum dolor, sit amet consectetur ndae voluptate amet. Doloribus laboriosam veritatis veniam magni quia iusto?</div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <br><br>
    <h5 class="h5">You may have like:</h5>
    <div class=" row d-flex justify-content-center">
        <div class="row"></div>
        <button class="col-xs-1 bg-light mt-3 mb-3 align-content-center d-flex flex-wrap"><h1 class="h1"><i class="fa fa-angle-left"></i></h1></button>
        <div class="col-xs-10"></div>
        {% for each in all_product|slice:4 %}
            <div class="col-md-2 col-sm-3 border p-3 m-3" >
                <img src="{{each.image_url}}" alt="">
                <h6 class="h6">{{each.product_name}}</h6>
                <div class="btn-group" >
                    <button class="btn btn-primary update-data" data-url="{% url 'cla:updateItem' %}" data-action="add" data-product="{{each.id}}" style="width:80%;">Add to Cart</button>
                    <a href="{% url 'cla:detail' each.id %}"><button class="btn btn-info"><i class="fa fa-expand"></i></button></a>
                </div>
                
            </div>
        {% endfor %}
        <button class="col-xs-1 bg-light mt-3 mb-3 align-content-center d-flex flex-wrap"><h1 class="h1"><i class="fa fa-angle-right"></i></h1></button>
    </div>
</div><br><br>
{% endblock content %}

templates/home_base.html
{% load static%}
{% load django_browser_reload %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- basic -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- mobile metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <meta http-equiv="cache-control" content="no-cache" />
        <!-- site metas -->
        <title>{% block title %}{% endblock title %} | C-L-A </title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- bootstrap css -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- style css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Responsive-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <!-- fevicon -->
        <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
        <!-- Tweaks for older IEs-->
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
     </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      
      <!-- end header inner -->
      <!-- end header -->
      <!-- banner -->
        <header>
            <!-- header inner -->
            <div class="header">
               <div class="container-fluid">
                  <div class="row">
                     <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                           <div class="center-desk">
                              <div class="logo">
                                 <a href="{% url 'cla:index' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <nav class="navigation navbar navbar-expand-md navbar-dark ">
                           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                           </button>
                           <div class="collapse navbar-collapse" id="navbarsExample04">
                              <ul class="navbar-nav mr-auto">
                                 <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'cla:index' %}">Home</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'cla:about' %}">About</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'cla:cart' %}">Cart <span class="badge badge-light mb-1">{{order.cart_items}}</span></a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'cla:product' %}">Products</a>
                                    <!-- <ul>
                                       <li class="">
                                          <a class="nav-link" href="{% url 'cla:computer' %}">Computer</a>
                                       </li>
                                       <li class="">
                                          <a class="nav-link" href="{% url 'cla:laptop' %}">Laptop</a>
                                       </li>
                                    </ul> -->
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'cla:contact' %}">Contact Us</a>
                                 </li>
                                 
                                 {% if user.is_authenticated %}
                                 <li class="nav-item">
                                    <h4 class="nav-text" style=" padding: 0 25p;color: rgb(90, 220, 249);font-size: 14px;line-height: 20px;font-weight: 500;">Hello, {{user.first_name}} <br>{{user.last_name}}</h4>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" id="confirm-logout" href="{% url 'accounts:logout' %}" onclick="return confirm('Are you sure you want to Logout?')">Logout</a>
                                 </li>
                                 {% else %}
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                                 </li>
                                 {% endif %}
                                 <li class="nav-item d_none">
                                    <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                                 </li>
                                 
                              </ul>
                           </div>
                        </nav>
                     </div>
                  </div>
               </div>
            </div>
         </header>
         <div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
               <strong>{{message}}</strong>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
               </div>
            {% endfor %}
            {% endif %}
         </div>
        {% block content %}


        {% endblock %}
            <!-- end contact -->
            <!--  footer -->
        <footer>
            <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <img class="logo1" src="{% static 'images/logo1.png' %}" alt="#"/>
                        <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <h3>About Us</h3>
                        <ul class="about_us">
                        <li>dolor sit amet, consectetur<br> magna aliqua. Ut enim ad <br>minim veniam, <br> quisdotempor incididunt r</li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <h3>Contact Us</h3>
                        <ul class="conta">
                        <li>dolor sit amet,<br> consectetur <br>magna aliqua.<br> quisdotempor <br>incididunt ut e </li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <form action="{% url 'accounts:subscribe' %}" class="bottom_form" method="post">
                           {% csrf_token %}
                           <h3>Newsletter</h3>
                           <input class="enter" placeholder="Enter your email" type="email" name="subscribe_email">
                           <button type="submit" class="sub_btn">subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                        <p>© 2019 All Rights Reserved. Design by<a href="'https://html.design/"> Free Html Templates</a></p>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </footer>
        <!-- end footer -->
        <!-- Javascript files-->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
        <!-- sidebar -->
        <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
        <script>
         function logout(){
            confirm('Are you sure you want logout')
         }
         
        </script>
        {% django_browser_reload_script %}
    </body>
</html>

templates/login.html
{% extends 'nohome_base.html' %}
{% block title %} Login {% endblock title %}
{% block content %}
{% if messages%}
{% for message in messages %}
<div class="container">
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>
</div>
{% endfor %}
{% endif %}
    <div class="contact">
        <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>Login Page</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <form id="request" class="main_form" action="{% url 'accounts:login' %}" method="post" aria-required="true">
                    {% csrf_token %}
                    <div class="row">
                    <div class="col-md-12 ">
                        <input class="contactus" placeholder="User Name" type="text" name="username" required> 
                    </div>
                    <div class="col-md-12">
                        <input class="contactus" placeholder="Password" type="password" name="password" required> 
                    </div>
                    <div class="col-md-12">
                        <button class="send_btn">Login</button>
                    </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/nohome_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <meta http-equiv="cache-control" content="no-cache" />
      <!-- site metas -->
      <title>{% block title %}{% endblock title %} | C-L-A</title>
      <meta name="keywords" content="Django Python E-website Sample">
      <meta name="description" content="">
      <meta name="author" content="Muhammed Fayis PV">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="{% url 'cla:index' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <!-- <li class="nav-item active">
                                 <a class="nav-link" href="{% url 'cla:index' %}">Home</a>
                              </li> -->
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'cla:about' %}">About</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'cla:cart' %}">Cart <span class="badge badge-light mb-1" id="count" value="{{count}}">{{count}}</span></a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'cla:product' %}">Products</a>
                                 <!-- <ul>
                                    <li class="">
                                       <a class="nav-link" href="{% url 'cla:computer' %}">Computer</a>
                                    </li>
                                    <li class="">
                                       <a class="nav-link" href="{% url 'cla:laptop' %}">Laptop</a>
                                    </li>
                                 </ul> -->
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'cla:contact' %}">Contact Us</a>
                              </li>
                              
                              {% if user.is_authenticated %}
                              <li class="nav-item">
                                 <h4 class="nav-text" style=" padding: 0 25p;color: rgb(90, 220, 249);font-size: 14px;line-height: 20px;font-weight: 500;">Hello, {{user.first_name}} <br>{{user.last_name}}</h4>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" id="confirm-logout" href="{% url 'accounts:logout' %}" onclick="return confirm('Are you sure you want to Logout?')">Logout</a>
                              </li>
                              {% else %}
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                              </li>
                              {% endif %}
                              <li class="nav-item d_none">
                                 <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                              </li>
                              
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      {% block content %} 


      {% endblock %}
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <img class="logo1" src="{% static 'images/logo1.png' %}" alt="#"/>
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <h3>About Us</h3>
                     <ul class="about_us">
                        <li>dolor sit amet, consectetur<br> magna aliqua. Ut enim ad <br>minim veniam, <br> quisdotempor incididunt r</li>
                     </ul>
                  </div>
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <h3>Contact Us</h3>
                     <ul class="conta">
                        <li>dolor sit amet,<br> consectetur <br>magna aliqua.<br> quisdotempor <br>incididunt ut e </li>
                     </ul>
                  </div>
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <form class="bottom_form">
                        <h3>Newsletter</h3>
                        <input class="enter" placeholder="Enter your email" type="email" name="subscribe_email">
                        <button class="sub_btn">subscribe</button>
                     </form>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <p>© 2019 All Rights Reserved. Design by<a href="{% static 'https://html.design/' %}"> Free Html Templates</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      {% block script %}
      {% endblock script %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      
      <script type="text/javascript">
         var user = '{{request.user}}'
         
         function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
         
      </script>
      <script>
         var updateData = document.getElementsByClassName('update-data')
       
                for(var i = 0;i<updateData.length;i++){
                   updateData[i].addEventListener('click',function(){
                      var productId = this.dataset.product
                      var action = this.dataset.action
                      var url = this.dataset.url
                      var itemQuantity = document.getElementById(productId)
                      var cardId = 'card-'+productId
                      var getCardId = document.getElementById(cardId)
                     // check()

                      console.log('productId: ' , productId, 'action: ',action,'url:',url)
                      console.log('User: ' ,user) 
                      if(user== 'Anonymoususer'){
                        console.log("Not logged In")
                      }else{
                        console.log('Logged In ...')
                        updateUserOrder(productId,action,url,itemQuantity,getCardId)
         
                      }
                      
                   })
                   
                 }
                 function updateUserOrder(productId,action,url,itemQuantity,getCardId){
                  var countBadge = document.getElementById('count')
                  var itemsCount = document.getElementById('items-count')
                  var allTotal = document.getElementById('all-total')

                  var itemQuantity =itemQuantity
                  var url = url
                  fetch(url,
                  {
                        method: 'POST',
                        headers: {
                           'Content-Type': 'application/json',
                           'X-CSRFToken': csrftoken
                        },
                      //  mode: 'same-origin', // Do not send CSRF token to another domain.
                        body : JSON.stringify({'productId':productId,'action':action}),
                     }
                  )
                  .then((response)=>{
                     return response.json()
                  })
                  .then((data)=>{
                     console.log('Data: ',data)
                     counts = data.counts
                     quantity = data.quantity
                     all_total = data.all_total
                     item_quantity = data.item_quantity
                     items_count = data.items_count
                     console.log('counts:',counts,
                     'all_total:',all_total,
                     'items_count:',items_count,
                     'item-quantity:',item_quantity
                     )
                     allTotal.innerHTML = all_total
                     
                   //  itemQuantity.innerHTML =item_quantity
                     itemsCount.innerHTML = items_count
                     console.log("0<",item_quantity)
                     if(item_quantity <= 0){
                        console.log('itemQuantityif:',item_quantity)
                        getCardId.className = 'd-none'}
                     else{itemQuantity.value = item_quantity}
                     countBadge.innerHTML = counts
                   //  location.reload()

                  }
                  ).catch(err=>{
                     console.log(err)
                  })
            
               }
       </script>
      
   </body> 
</html>

templates/product.html
{% extends 'nohome_base.html' %}
{% load static %}
{% block title %} Product {% endblock title %}
{% block content %}
<!-- products -->
<div class="products">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="titlepage ">
               <h2 style="margin: auto;">Our Products</h2>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-12">
            <div class="our_products"> 
               <div class="row">
                  {% if rand_product_list %}
                  {% for product in rand_product_list %}
                  <div class="col-md-4 margin_bottom1">
                     <div class="product_box">
                        <figure><img src="{{product.product_img.url}}" alt="#"/></figure>
                        <h3>{{product.product_name}}</h3>
                        <button data-action="add" data-url="{% url 'cla:updateItem' %}" data-product="{{product.id}}" style="width: 57%;" class="btn btn-primary update-data">+Add to Cart</button>
                        <a href="{% url 'cla:detail' product.id %}"><button class="btn btn-info"><i class="fa fa-expand"></i></button></a>
                     </div> <input type="hidden" id="all-total" value=""><input type="hidden" id="items-count" value=""><input type="hidden" id="card-2" value="">
                  </div>
                  {% endfor %}
                  {% endif %}
                  <div class="col-md-12">
                     <a class="read_more" href="#">See More</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- end products -->
{% endblock content %}